CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS GESTANTE (
    ID_GESTANTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOME_GESTANTE VARCHAR(100) NOT NULL,
    RG VARCHAR(18) NOT NULL,
    RACA VARCHAR(20) NOT NULL,
    CONTATO NUMERIC NOT NULL,
    CONSTRAINT FK_GESTANTE_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS DADOS_GRAVIDEZ (
    ID_DADOS_GRAVIDEZ INT AUTO_INCREMENT PRIMARY KEY,
    ID_GESTANTE INT NOT NULL,
    IDADE_GESTANTE INT NOT NULL,
    PRESSAO_SANGUINEA_SISTOLICA FLOAT NOT NULL,
    PRESSAO_SANGUINEA_DIASTOLICA FLOAT NOT NULL,
    NIVEL_GLICOSE_SANGUE FLOAT NOT NULL,
    FREQUENCIA_CARDIACA FLOAT NOT NULL,
    TEMPERATURA_CORPORAL_GRAVIDEZ NUMBER NOT NULL,
    RISCO_GRAVIDEZ VARCHAR(30),
    DATA_AVALIACAO TIMESTAMP,
    CONSTRAINT FK_DADOS_GRAVIDEZ_GESTANTE FOREIGN KEY (ID_GESTANTE)
        REFERENCES GESTANTE(ID_GESTANTE)
);

CREATE TABLE IF NOT EXISTS FETO (
    ID_FETO INT AUTO_INCREMENT PRIMARY KEY,
    ID_GESTANTE INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IDADE_SEMANAS INT NOT NULL,
    SEXO VARCHAR(11) NOT NULL,
    CONSTRAINT FK_FETO_GESTANTE FOREIGN KEY (ID_GESTANTE)
        REFERENCES GESTANTE(ID_GESTANTE)
);

CREATE TABLE IF NOT EXISTS DADOS_FETO (
    ID_DADOS_FETO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FETO NUMBER NOT NULL,
	IDADE INTEGER NOT NULL,
	FREQUENCIA_CARDIACA NUMBER NOT NULL,
	ACELERACOES NUMBER NOT NULL,
	MOVIMENTO_FETAL_POR_SEGUNDO NUMBER NOT NULL,
	CONTRACOES NUMBER NOT NULL,
	DESACELERACOES VARCHAR(30),
	DESACELERACOES_SEVERAS NUMBER NOT NULL,
	DESACELERACOES_PROLONGADAS NUMBER NOT NULL,
	VARIACAO_ANORMAL_CURTO_PRAZO NUMBER NOT NULL,
	VARIACAO_MEDIA_CURTO_PRAZO NUMBER NOT NULL,
	PORCENTAGEM_TEMPO_VARIACAO_ANORMAL NUMBER NOT NULL,
	MEDIA_VARIACAO_LONGO_PRAZO NUMBER NOT NULL,
	LARGURA_HISTOGRAMA NUMBER NOT NULL,
	VALOR_MININO_HISTOGRAMA NUMBER NOT NULL,
	VALOR_MAXIMO_HISTOGRAMA NUMBER NOT NULL,
	NUMERO_PICOS_HISTOGRAMA NUMBER NOT NULL,
	NUMERO_ZEROS_HISTOGRAMA NUMBER NOT NULL,
	MODULO_HISTOGRAMA NUMBER NOT NULL,
	MEDIA_HISTOGRAMA NUMBER NOT NULL,
	MEDIANA_HISTOGRAMA NUMBER NOT NULL,
	VARIANCIA_HISTOGRAMA NUMBER NOT NULL,
	TENDENCIA_HISTOGRAMA NUMBER NOT NULL,
	SAUDE_FETO VARCHAR(15),
	DATA_AVALIACAO TIMESTAMP,
	CONSTRAINT FK_DADOS_FETO FOREIGN KEY (ID_FETO)
		REFERENCES FETO(ID_FETO)
);


