CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS GESTANTE (
    ID_GESTANTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOME_GESTANTE VARCHAR(100) NOT NULL,
    RG VARCHAR(18) NOT NULL,
    RACA VARCHAR(20) NOT NULL,
    CONTATO NUMERIC NOT NULL,
    CONSTRAINT FK_GESTANTE_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS DADOS_GRAVIDEZ (
    ID_DADOS_GRAVIDEZ INT AUTO_INCREMENT PRIMARY KEY,
    ID_GESTANTE INT NOT NULL,
    IDADE INT NOT NULL,
    PRESSAO_SANGUINEA_SISTOLICA FLOAT NOT NULL,
    PRESSAO_SANGUINEA_DIASTOLICA FLOAT NOT NULL,
    NIVEL_GLICOSE_SANGUE FLOAT NOT NULL,
    FREQUENCIA_CARDIACA FLOAT NOT NULL,
    RISCO_GRAVIDEZ VARCHAR(30),
    CONSTRAINT FK_DADOS_GRAVIDEZ_GESTANTE FOREIGN KEY (ID_GESTANTE)
        REFERENCES GESTANTE(ID_GESTANTE)
);

CREATE TABLE IF NOT EXISTS FETO (
    ID_FETO INT AUTO_INCREMENT PRIMARY KEY,
    ID_GESTANTE INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IDADE_SEMANAS INT NOT NULL,
    SEXO VARCHAR(11) NOT NULL,
    CONSTRAINT FK_FETO_GESTANTE FOREIGN KEY (ID_GESTANTE)
        REFERENCES GESTANTE(ID_GESTANTE)
);

CREATE TABLE IF NOT EXISTS DADOS_FETO (
    ID_DADOS_FETO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FETO INT NOT NULL,
    IDADE INT NOT NULL,
    FREQUENCIA_CARDIACA FLOAT NOT NULL,
    ACELERACOES FLOAT NOT NULL,
    MOVIMENTO_FETAL_POR_SEGUNDO FLOAT NOT NULL,
    CONTRACOES FLOAT NOT NULL,
    DESACELERACOES FLOAT NOT NULL,
    DESACELERACOES_SEVERAS FLOAT NOT NULL,
    DESACELERACOES_PROLONGADAS FLOAT NOT NULL,
    VARIACAO_ANORMAL_CURTO_PRAZO FLOAT NOT NULL,
    VARIACAO_MEDIA_CURTO_PRAZO FLOAT NOT NULL,
    PORCENTAGEM_TEMPO_VARIACAO_ANORMAL FLOAT NOT NULL,
    MEDIA_VARIACAO_LONGO_PRAZO FLOAT NOT NULL,
    SAUDE_FETO VARCHAR(15),
    CONSTRAINT FK_DADOS_FETO FOREIGN KEY (ID_FETO)
        REFERENCES FETO(ID_FETO)
);
